/*----- PROTECTED REGION ID(DCS210PCStateMachine.cpp) ENABLED START -----*/
/* clang-format on */
//=============================================================================
//
// file :        DCS210PCStateMachine.cpp
//
// description : State machine file for the DCS210PC class
//
//
//
// This file is part of Tango device class.
//
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
//
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include "DCS210PC.h"

/* clang-format off */
/*----- PROTECTED REGION END -----*/	//	DCS210PC::DCS210PCStateMachine.cpp

//================================================================
//  States  |  Description
//================================================================
//  ON      |  
//  OFF     |  
//  CLOSE   |  
//  OPEN    |  
//  FAULT   |  


namespace DCS210PC_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method     : DCS210PC::is_photons_num_str_allowed()
 *	Description: Execution allowed for photons_num_str attribute
 */
//--------------------------------------------------------
bool DCS210PC::is_photons_num_str_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for photons_num_str attribute in read access.
	/*----- PROTECTED REGION ID(DCS210PC::photons_num_strStateAllowed_READ) ENABLED START -----*/
	/* clang-format on */
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	DCS210PC::photons_num_strStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method     : DCS210PC::is_count_samplingtime_allowed()
 *	Description: Execution allowed for count_samplingtime attribute
 */
//--------------------------------------------------------
bool DCS210PC::is_count_samplingtime_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for count_samplingtime attribute in Write access.
	/*----- PROTECTED REGION ID(DCS210PC::count_samplingtimeStateAllowed_WRITE) ENABLED START -----*/
	/* clang-format on */
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	DCS210PC::count_samplingtimeStateAllowed_WRITE

	return true;
}

//--------------------------------------------------------
/**
 *	Method     : DCS210PC::is_photon_num_int_allowed()
 *	Description: Execution allowed for photon_num_int attribute
 */
//--------------------------------------------------------
bool DCS210PC::is_photon_num_int_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for photon_num_int attribute in read access.
	/*----- PROTECTED REGION ID(DCS210PC::photon_num_intStateAllowed_READ) ENABLED START -----*/
	/* clang-format on */
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	DCS210PC::photon_num_intStateAllowed_READ
	return true;
}


//=================================================
//		Commands Allowed Methods
//=================================================


/*----- PROTECTED REGION ID(DCS210PC::DCS210PCStateAllowed.AdditionalMethods) ENABLED START -----*/
/* clang-format on */
//	Additional Methods
/* clang-format off */
/*----- PROTECTED REGION END -----*/	//	DCS210PC::DCS210PCStateAllowed.AdditionalMethods

}	//	End of namespace
