/*----- PROTECTED REGION ID(DCS210PC.cpp) ENABLED START -----*/
/* clang-format on */
//=============================================================================
//
// file :        DCS210PC.cpp
//
// description : C++ source for the DCS210PC class and its commands.
//               The class is derived from Device. It represents the
//               CORBA servant object which will be accessed from the
//               network. All commands which can be executed on the
//               DCS210PC are implemented in this file.
//
//
//
// This file is part of Tango device class.
//
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
//
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include "DCS210PC.h"
#include "DCS210PCClass.h"
//#include "serial_port.h"
/* clang-format off */
/*----- PROTECTED REGION END -----*/	//	DCS210PC.cpp

/**
 *  DCS210PC class description:
 *    
 */

//================================================================
//  The following table gives the correspondence
//  between command and method names.
//
//  Command name  |  Method name
//================================================================
//  State         |  Inherited (no method)
//  Status        |  Inherited (no method)
//================================================================

//================================================================
//  Attributes managed are:
//================================================================
//  photons_num_str  |  Tango::DevString	Scalar
//  photon_num_int   |  Tango::DevLong	Spectrum  ( max = 100000)
//================================================================

namespace DCS210PC_ns
{
/*----- PROTECTED REGION ID(DCS210PC::namespace_starting) ENABLED START -----*/
/* clang-format on */
//	static initializations
int photon_buffer_index;
int photon_buffer_count;


/* clang-format off */
/*----- PROTECTED REGION END -----*/	//	DCS210PC::namespace_starting

//--------------------------------------------------------
/**
 *	Method     : DCS210PC::DCS210PC()
 *	Description: Constructors for a Tango device
 *                implementing the classDCS210PC
 */
//--------------------------------------------------------
DCS210PC::DCS210PC(Tango::DeviceClass *cl, std::string &s)
 : TANGO_BASE_CLASS(cl, s.c_str())
{
	/*----- PROTECTED REGION ID(DCS210PC::constructor_1) ENABLED START -----*/
	/* clang-format on */
	init_device();
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	DCS210PC::constructor_1
}
//--------------------------------------------------------
DCS210PC::DCS210PC(Tango::DeviceClass *cl, const char *s)
 : TANGO_BASE_CLASS(cl, s)
{
	/*----- PROTECTED REGION ID(DCS210PC::constructor_2) ENABLED START -----*/
	/* clang-format on */
	init_device();
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	DCS210PC::constructor_2
}
//--------------------------------------------------------
DCS210PC::DCS210PC(Tango::DeviceClass *cl, const char *s, const char *d)
 : TANGO_BASE_CLASS(cl, s, d)
{
	/*----- PROTECTED REGION ID(DCS210PC::constructor_3) ENABLED START -----*/
	/* clang-format on */
	init_device();
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	DCS210PC::constructor_3
}
//--------------------------------------------------------
DCS210PC::~DCS210PC()
{
	delete_device();
}

//--------------------------------------------------------
/**
 *	Method     : DCS210PC::delete_device()
 *	Description: will be called at device destruction or at init command
 */
//--------------------------------------------------------
void DCS210PC::delete_device()
{
	DEBUG_STREAM << "DCS210PC::delete_device() " << device_name << std::endl;
	/*----- PROTECTED REGION ID(DCS210PC::delete_device) ENABLED START -----*/
	/* clang-format on */
	//	Delete device allocated objects
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	DCS210PC::delete_device
	delete[] attr_photons_num_str_read;
	delete[] attr_photon_num_int_read;
}

//--------------------------------------------------------
/**
 *	Method     : DCS210PC::init_device()
 *	Description: will be called at device initialization.
 */
//--------------------------------------------------------
void DCS210PC::init_device()
{
	DEBUG_STREAM << "DCS210PC::init_device() create device " << device_name << std::endl;
	/*----- PROTECTED REGION ID(DCS210PC::init_device_before) ENABLED START -----*/
	/* clang-format on */
	//	Initialization before get_device_property() call
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	DCS210PC::init_device_before


	//	Get the device properties from database
	get_device_property();

	attr_photons_num_str_read = new Tango::DevString[1];
	attr_photon_num_int_read = new Tango::DevLong[photon_num_intAttrib::X_DATA_SIZE];
	/*----- PROTECTED REGION ID(DCS210PC::init_device) ENABLED START -----*/
	/* clang-format on */
	//	Initialize device
	/* clang-format off */

	this->fd = serial_port_open((char *) (this->com.c_str()), 9600);
        
	if (this->fd < 0) {
		set_state(Tango::DevState::FAULT);
	} else {
		set_state(Tango::DevState::OPEN);
	}

	char response[256];
	int bytesRead = serial_port_write_read(this->fd, "Hello", response, sizeof(response), 100);

	if ((std::string)response != "OK\r") set_state(Tango::DevState::FAULT);
	bytesRead = serial_port_write_read(this->fd, "RESTORE", response, sizeof(response), 100);
	bytesRead = serial_port_write_read(this->fd, "COUNT_MODE 3", response, sizeof(response), 100);
	bytesRead = serial_port_write_read(this->fd, "DAQ_MODE Q", response, sizeof(response), 100);
	bytesRead = serial_port_write_read(this->fd, "COUNT_SAMPLINGTIME 1000000", response, sizeof(response), 100);
	bytesRead = serial_port_write_read(this->fd, "COUNT_DWELLTIME 1500000", response, sizeof(response), 100);

	// for (int i = 0; i < 1024; i++) {
    // 	attr_photon_num_int_read[i] = 0;
    // }
    photon_buffer_index = 0;
    photon_buffer_count = 0;
	




	/*----- PROTECTED REGION END -----*/	//	DCS210PC::init_device
}

//--------------------------------------------------------
/**
 *	Method     : DCS210PC::get_device_property()
 *	Description: Read database to initialize property data members.
 */
//--------------------------------------------------------
void DCS210PC::get_device_property()
{
	/*----- PROTECTED REGION ID(DCS210PC::get_device_property_before) ENABLED START -----*/
	/* clang-format on */
	//	Initialize property data members
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	DCS210PC::get_device_property_before


	//	Read device properties from database.
	Tango::DbData	dev_prop;
	dev_prop.push_back(Tango::DbDatum("baudrade"));
	dev_prop.push_back(Tango::DbDatum("com"));

	//	is there at least one property to be read ?
	if (dev_prop.size()>0)
	{
		//	Call database and extract values
		if (Tango::Util::instance()->_UseDb==true)
			get_db_device()->get_property(dev_prop);

		//	get instance on DCS210PCClass to get class property
		Tango::DbDatum	def_prop, cl_prop;
		DCS210PCClass	*ds_class =
			(static_cast<DCS210PCClass *>(get_device_class()));
		int	i = -1;

		//	Try to initialize baudrade from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  baudrade;
		else {
			//	Try to initialize baudrade from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  baudrade;
		}
		//	And try to extract baudrade value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  baudrade;

		//	Try to initialize com from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  com;
		else {
			//	Try to initialize com from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  com;
		}
		//	And try to extract com value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  com;

	}

	/*----- PROTECTED REGION ID(DCS210PC::get_device_property_after) ENABLED START -----*/
	/* clang-format on */
	//	Check device property data members init
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	DCS210PC::get_device_property_after
}

//--------------------------------------------------------
/**
 *	Method     : DCS210PC::always_executed_hook()
 *	Description: method always executed before any command is executed
 */
//--------------------------------------------------------
void DCS210PC::always_executed_hook()
{
	DEBUG_STREAM << "DCS210PC::always_executed_hook()  " << device_name << std::endl;
	/*----- PROTECTED REGION ID(DCS210PC::always_executed_hook) ENABLED START -----*/
	/* clang-format on */
	//	code always executed before all requests
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	DCS210PC::always_executed_hook
}

//--------------------------------------------------------
/**
 *	Method     : DCS210PC::read_attr_hardware()
 *	Description: Hardware acquisition for attributes
 */
//--------------------------------------------------------
void DCS210PC::read_attr_hardware(TANGO_UNUSED(std::vector<long> &attr_list))
{
	DEBUG_STREAM << "DCS210PC::read_attr_hardware(std::vector<long> &attr_list) entering... " << std::endl;
	/*----- PROTECTED REGION ID(DCS210PC::read_attr_hardware) ENABLED START -----*/
	/* clang-format on */
	//	Add your own code
	/* clang-format off */
	char response[256];
	int bytesRead = serial_port_write_read(this->fd, "DATA_COUNT?", response, sizeof(response), 100);
	this->count_ph = (std::string)response;
	/*----- PROTECTED REGION END -----*/	//	DCS210PC::read_attr_hardware
}

//--------------------------------------------------------
/**
 *	Read attribute photons_num_str related method
 *
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void DCS210PC::read_photons_num_str(Tango::Attribute &attr)
{
	DEBUG_STREAM << "DCS210PC::read_photons_num_str(Tango::Attribute &attr) entering... " << std::endl;
	/*----- PROTECTED REGION ID(DCS210PC::read_photons_num_str) ENABLED START -----*/
	/* clang-format on */
	//	Set the attribute value
	*this->attr_photons_num_str_read = Tango::string_dup(this->count_ph.c_str());
	attr.set_value(attr_photons_num_str_read);
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	DCS210PC::read_photons_num_str
}
//--------------------------------------------------------
/**
 *	Read attribute photon_num_int related method
 *
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Spectrum max = 100000
 */
//--------------------------------------------------------
void DCS210PC::read_photon_num_int(Tango::Attribute &attr)
{
	DEBUG_STREAM << "DCS210PC::read_photon_num_int(Tango::Attribute &attr) entering... " << std::endl;
	/*----- PROTECTED REGION ID(DCS210PC::read_photon_num_int) ENABLED START -----*/
	/* clang-format on */
	//	Set the attribute value

	const char* prefix = "DATA_COUNT?";
	size_t pos = this->count_ph.find(prefix);

	if (pos != std::string::npos) {
		// Перемещаем позицию на конец префикса
		pos += strlen(prefix);
		
		// Пропускаем пробелы
		while (pos < this->count_ph.length() && 
			(this->count_ph[pos] == ' ' || this->count_ph[pos] == '\t')) {
			pos++;
		}
		
		if (pos < this->count_ph.length()) {
			char* endptr;
			// Получаем C-строку начиная с нужной позиции
			const char* numStr = this->count_ph.c_str() + pos;
			int count = strtol(numStr, &endptr, 10);
			
			// Проверяем, что было считано хотя бы одно число
			if (endptr != numStr) {
				attr_photon_num_int_read[photon_buffer_index] = count;
				photon_buffer_index = (photon_buffer_index + 1) % 100000;
				if (photon_buffer_count < 100000) {
					photon_buffer_count++;
				}
			}
		}
	}
	attr.set_value(attr_photon_num_int_read, photon_buffer_count);
	// attr.set_value(attr_photon_num_int_read, photon_num_intAttrib::X_DATA_SIZE);
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	DCS210PC::read_photon_num_int
}

//--------------------------------------------------------
/**
 *	Method     : DCS210PC::add_dynamic_attributes()
 *	Description: Create the dynamic attributes if any
 *                for specified device.
 */
//--------------------------------------------------------
void DCS210PC::add_dynamic_attributes()
{
	/*----- PROTECTED REGION ID(DCS210PC::add_dynamic_attributes) ENABLED START -----*/
	/* clang-format on */
	//	Add your own code to create and add dynamic attributes if any
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	DCS210PC::add_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Method     : DCS210PC::add_dynamic_commands()
 *	Description: Create the dynamic commands if any
 *                for specified device.
 */
//--------------------------------------------------------
void DCS210PC::add_dynamic_commands()
{
	/*----- PROTECTED REGION ID(DCS210PC::add_dynamic_commands) ENABLED START -----*/
	/* clang-format on */
	//	Add your own code to create and add dynamic commands if any
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	DCS210PC::add_dynamic_commands
}

/*----- PROTECTED REGION ID(DCS210PC::namespace_ending) ENABLED START -----*/
/* clang-format on */
//	Additional Methods
/* clang-format off */
/*----- PROTECTED REGION END -----*/	//	DCS210PC::namespace_ending
} //	namespace
