/*----- PROTECTED REGION ID(DCS210PCClass.h) ENABLED START -----*/
/* clang-format on */
//=============================================================================
//
// file :        DCS210PCClass.h
//
// description : Include for the DCS210PC root class.
//               This class is the singleton class for
//                the DCS210PC device class.
//               It contains all properties and methods which the
//               DCS210PC requires only once e.g. the commands.
//
//
//
// This file is part of Tango device class.
//
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
//
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef DCS210PCClass_H
#define DCS210PCClass_H

#include <tango/tango.h>
#include "DCS210PC.h"

/* clang-format off */
/*----- PROTECTED REGION END -----*/	//	DCS210PCClass.h


namespace DCS210PC_ns
{
/*----- PROTECTED REGION ID(DCS210PCClass::classes for dynamic creation) ENABLED START -----*/
/* clang-format on */

/* clang-format off */
/*----- PROTECTED REGION END -----*/	//	DCS210PCClass::classes for dynamic creation

//=========================================
//	Define classes for attributes
//=========================================
//	Attribute photons_num_str class definition
class photons_num_strAttrib: public Tango::Attr
{
public:
	photons_num_strAttrib():Attr("photons_num_str",
			Tango::DEV_STRING, Tango::READ) {}
	~photons_num_strAttrib() {}
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<DCS210PC *>(dev))->read_photons_num_str(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<DCS210PC *>(dev))->is_photons_num_str_allowed(ty);}
};

//	Attribute photon_num_int class definition
class photon_num_intAttrib: public Tango::SpectrumAttr
{
public:
	// Constants for photon_num_int attribute
	constexpr static long X_DATA_SIZE = 100000;
	photon_num_intAttrib():SpectrumAttr("photon_num_int",
			Tango::DEV_LONG, Tango::READ, photon_num_intAttrib::X_DATA_SIZE) {}
	~photon_num_intAttrib() {}
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<DCS210PC *>(dev))->read_photon_num_int(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<DCS210PC *>(dev))->is_photon_num_int_allowed(ty);}
};


/**
 *	The DCS210PCClass singleton definition
 */

#ifdef _TG_WINDOWS_
class __declspec(dllexport)  DCS210PCClass : public Tango::DeviceClass
#else
class DCS210PCClass : public Tango::DeviceClass
#endif
{
	/*----- PROTECTED REGION ID(DCS210PCClass::Additional DServer data members) ENABLED START -----*/
	/* clang-format on */
	//	Add your own code
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	DCS210PCClass::Additional DServer data members

	public:
		//	write class properties data members
		Tango::DbData	cl_prop;
		Tango::DbData	cl_def_prop;
		Tango::DbData	dev_def_prop;
		//	Method prototypes
		static DCS210PCClass *init(const char *);
		static DCS210PCClass *instance();
		~DCS210PCClass();
		Tango::DbDatum	get_class_property(std::string &);
		Tango::DbDatum	get_default_device_property(std::string &);
		Tango::DbDatum	get_default_class_property(std::string &);

	protected:
		DCS210PCClass(std::string &);
		static DCS210PCClass *_instance;
		void command_factory();
		void attribute_factory(std::vector<Tango::Attr *> &);
		void pipe_factory();
		void write_class_property();
		void set_default_property();
		void get_class_property();
		std::string get_cvstag();
		std::string get_cvsroot();

	private:
		void device_factory(TANGO_UNUSED(const Tango::DevVarStringArray *));
		void create_static_attribute_list(std::vector<Tango::Attr *> &);
		void erase_dynamic_attributes(const Tango::DevVarStringArray *,std::vector<Tango::Attr *> &);
		std::vector<std::string>	defaultAttList;
		Tango::Attr *get_attr_object_by_name(std::vector<Tango::Attr *> &att_list, std::string attname);
};

}	//	End of namespace

#endif   //	DCS210PC_H
