/*----- PROTECTED REGION ID(DCS210PCClass.cpp) ENABLED START -----*/
/* clang-format on */
//=============================================================================
//
// file :        DCS210PCClass.cpp
//
// description : C++ source for the DCS210PCClass.
//               A singleton class derived from DeviceClass.
//               It implements the command and attribute list
//               and all properties and methods required
//               by the DCS210PC once per process.
//
//
//
// This file is part of Tango device class.
//
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
//
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include "DCS210PCClass.h"
/* clang-format off */
/*----- PROTECTED REGION END -----*/	//	DCS210PCClass.cpp

//-------------------------------------------------------------------
/**
 *	Create DCS210PCClass singleton and
 *	return it in a C function for Python usage
 */
//-------------------------------------------------------------------
extern "C" {
#ifdef _TG_WINDOWS_

__declspec(dllexport)

#endif

	Tango::DeviceClass *_create_DCS210PC_class(const char *name) {
		return DCS210PC_ns::DCS210PCClass::init(name);
	}
}

namespace DCS210PC_ns
{
//===================================================================
//	Initialize pointer for singleton pattern
//===================================================================
DCS210PCClass *DCS210PCClass::_instance = nullptr;

//===================================================================
//	Class constants
//===================================================================
//--------------------------------------------------------
/**
 * method : 		DCS210PCClass::DCS210PCClass(std::string &s)
 * description : 	constructor for the DCS210PCClass
 *
 * @param s	The class name
 */
//--------------------------------------------------------
DCS210PCClass::DCS210PCClass(std::string &s):Tango::DeviceClass(s)
{
	TANGO_LOG_INFO << "Entering DCS210PCClass constructor" << std::endl;
	set_default_property();
	write_class_property();

	/*----- PROTECTED REGION ID(DCS210PCClass::constructor) ENABLED START -----*/
	/* clang-format on */
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	DCS210PCClass::constructor

	TANGO_LOG_INFO << "Leaving DCS210PCClass constructor" << std::endl;
}

//--------------------------------------------------------
/**
 * method : 		DCS210PCClass::~DCS210PCClass()
 * description : 	destructor for the DCS210PCClass
 */
//--------------------------------------------------------
DCS210PCClass::~DCS210PCClass()
{
	/*----- PROTECTED REGION ID(DCS210PCClass::destructor) ENABLED START -----*/
	/* clang-format on */
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	DCS210PCClass::destructor

	_instance = nullptr;
}


//--------------------------------------------------------
/**
 * method : 		DCS210PCClass::init
 * description : 	Create the object if not already done.
 *                  Otherwise, just return a pointer to the object
 *
 * @param	name	The class name
 */
//--------------------------------------------------------
DCS210PCClass *DCS210PCClass::init(const char *name)
{
	if (_instance == nullptr)
	{
		try
		{
			std::string s(name);
			_instance = new DCS210PCClass(s);
		}
		catch (std::bad_alloc &)
		{
			throw;
		}
	}
	return _instance;
}

//--------------------------------------------------------
/**
 * method : 		DCS210PCClass::instance
 * description : 	Check if object already created,
 *                  and return a pointer to the object
 */
//--------------------------------------------------------
DCS210PCClass *DCS210PCClass::instance()
{
	if (_instance == nullptr)
	{
		std::cerr << "Class is not initialized !!" << std::endl;
		exit(-1);
	}
	return _instance;
}



//===================================================================
//	Command execution method calls
//===================================================================

//===================================================================
//	Properties management
//===================================================================
//--------------------------------------------------------
/**
 *	Method     : DCS210PCClass::get_class_property()
 *	Description: Get the class property for specified name.
 */
//--------------------------------------------------------
Tango::DbDatum DCS210PCClass::get_class_property(std::string &prop_name)
{
	for (unsigned int i=0 ; i<cl_prop.size() ; i++)
		if (cl_prop[i].name == prop_name)
			return cl_prop[i];
	//	if not found, returns  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method     : DCS210PCClass::get_default_device_property()
 *	Description: Return the default value for device property.
 */
//--------------------------------------------------------
Tango::DbDatum DCS210PCClass::get_default_device_property(std::string &prop_name)
{
	for (unsigned int i=0 ; i<dev_def_prop.size() ; i++)
		if (dev_def_prop[i].name == prop_name)
			return dev_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method     : DCS210PCClass::get_default_class_property()
 *	Description: Return the default value for class property.
 */
//--------------------------------------------------------
Tango::DbDatum DCS210PCClass::get_default_class_property(std::string &prop_name)
{
	for (unsigned int i=0 ; i<cl_def_prop.size() ; i++)
		if (cl_def_prop[i].name == prop_name)
			return cl_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}


//--------------------------------------------------------
/**
 *	Method     : DCS210PCClass::set_default_property()
 *	Description: Set default property (class and device) for wizard.
 *                For each property, add to wizard property name and description.
 *                If default value has been set, add it to wizard property and
 *                store it in a DbDatum.
 */
//--------------------------------------------------------
void DCS210PCClass::set_default_property()
{
	std::string	prop_name;
	std::string	prop_desc;
	std::string	prop_def;
	std::vector<std::string>	vect_data;

	//	Set Default Class Properties

	//	Set Default device Properties
	prop_name = "baudrade";
	prop_desc = "";
	prop_def  = "9600";
	vect_data.clear();
	vect_data.push_back("9600");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "com";
	prop_desc = "";
	prop_def  = "/dev/ttyUSB0";
	vect_data.clear();
	vect_data.push_back("/dev/ttyUSB0");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
}

//--------------------------------------------------------
/**
 *	Method     : DCS210PCClass::write_class_property()
 *	Description: Set class description fields as property in database
 */
//--------------------------------------------------------
void DCS210PCClass::write_class_property()
{
	//	First time, check if database used
	if (Tango::Util::_UseDb == false)
		return;

	Tango::DbData	data;
	std::string	classname = get_name();
	std::string	header;

	//	Put title
	Tango::DbDatum	title("ProjectTitle");
	std::string	str_title("");
	title << str_title;
	data.push_back(title);

	//	Put Description
	Tango::DbDatum	description("Description");
	std::vector<std::string>	str_desc;
	str_desc.push_back("");
	description << str_desc;
	data.push_back(description);

	//  Put inheritance
	Tango::DbDatum	inher_datum("InheritedFrom");
	std::vector<std::string> inheritance;
	inheritance.push_back("TANGO_BASE_CLASS");
	inher_datum << inheritance;
	data.push_back(inher_datum);

	//	Call database and and values
	get_db_class()->put_property(data);
}

//===================================================================
//	Factory methods
//===================================================================

//--------------------------------------------------------
/**
 *	Method     : DCS210PCClass::device_factory()
 *	Description: Create the device object(s)
 *                and store them in the device list
 */
//--------------------------------------------------------
void DCS210PCClass::device_factory(const Tango::DevVarStringArray *devlist_ptr)
{
	/*----- PROTECTED REGION ID(DCS210PCClass::device_factory_before) ENABLED START -----*/
	/* clang-format on */
	//	Add your own code
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	DCS210PCClass::device_factory_before

	//	Create devices and add it into the device list
	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		TANGO_LOG_DEBUG << "Device name : " << (*devlist_ptr)[i].in() << std::endl;
		device_list.push_back(new DCS210PC(this, (*devlist_ptr)[i]));
	}

	//	Manage dynamic attributes if any
	erase_dynamic_attributes(devlist_ptr, get_class_attr()->get_attr_list());

	//	Export devices to the outside world
	for (unsigned long i=1 ; i<=devlist_ptr->length() ; i++)
	{
		//	Add dynamic attributes if any
		DCS210PC *dev = static_cast<DCS210PC *>(device_list[device_list.size()-i]);
		dev->add_dynamic_attributes();

		//	Check before if database used.
		if ((Tango::Util::_UseDb == true) && (Tango::Util::_FileDb == false))
			export_device(dev);
		else
			export_device(dev, dev->get_name().c_str());
	}

	/*----- PROTECTED REGION ID(DCS210PCClass::device_factory_after) ENABLED START -----*/
	/* clang-format on */
	//	Add your own code
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	DCS210PCClass::device_factory_after
}
//--------------------------------------------------------
/**
 *	Method     : DCS210PCClass::attribute_factory()
 *	Description: Create the attribute object(s)
 *                and store them in the attribute list
 */
//--------------------------------------------------------
void DCS210PCClass::attribute_factory([[maybe_unused]] std::vector<Tango::Attr *> &att_list)
{
	/*----- PROTECTED REGION ID(DCS210PCClass::attribute_factory_before) ENABLED START -----*/
	/* clang-format on */
	//	Add your own code
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	DCS210PCClass::attribute_factory_before
	//	Attribute : photons_num_str
	photons_num_strAttrib	*photons_num_str = new photons_num_strAttrib();
	Tango::UserDefaultAttrProp	photons_num_str_prop;
	//	description	not set for photons_num_str
	//	label	not set for photons_num_str
	//	unit	not set for photons_num_str
	//	standard_unit	not set for photons_num_str
	//	display_unit	not set for photons_num_str
	//	format	not set for photons_num_str
	//	max_value	not set for photons_num_str
	//	min_value	not set for photons_num_str
	//	max_alarm	not set for photons_num_str
	//	min_alarm	not set for photons_num_str
	//	max_warning	not set for photons_num_str
	//	min_warning	not set for photons_num_str
	//	delta_t	not set for photons_num_str
	//	delta_val	not set for photons_num_str
	photons_num_str->set_default_properties(photons_num_str_prop);
	//	Not Polled
	photons_num_str->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(photons_num_str);

	//	Attribute : photon_num_int
	photon_num_intAttrib	*photon_num_int = new photon_num_intAttrib();
	Tango::UserDefaultAttrProp	photon_num_int_prop;
	//	description	not set for photon_num_int
	//	label	not set for photon_num_int
	//	unit	not set for photon_num_int
	//	standard_unit	not set for photon_num_int
	//	display_unit	not set for photon_num_int
	//	format	not set for photon_num_int
	//	max_value	not set for photon_num_int
	//	min_value	not set for photon_num_int
	//	max_alarm	not set for photon_num_int
	//	min_alarm	not set for photon_num_int
	//	max_warning	not set for photon_num_int
	//	min_warning	not set for photon_num_int
	//	delta_t	not set for photon_num_int
	//	delta_val	not set for photon_num_int
	photon_num_int->set_default_properties(photon_num_int_prop);
	//	Not Polled
	photon_num_int->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(photon_num_int);


	//	Create a list of static attributes
	create_static_attribute_list(get_class_attr()->get_attr_list());
	/*----- PROTECTED REGION ID(DCS210PCClass::attribute_factory_after) ENABLED START -----*/
	/* clang-format on */
	//	Add your own code
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	DCS210PCClass::attribute_factory_after
}
//--------------------------------------------------------
/**
 *	Method     : DCS210PCClass::pipe_factory()
 *	Description: Create the pipe object(s)
 *                and store them in the pipe list
 */
//--------------------------------------------------------
void DCS210PCClass::pipe_factory()
{
	/*----- PROTECTED REGION ID(DCS210PCClass::pipe_factory_before) ENABLED START -----*/
	/* clang-format on */
	//	Add your own code
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	DCS210PCClass::pipe_factory_before
	/*----- PROTECTED REGION ID(DCS210PCClass::pipe_factory_after) ENABLED START -----*/
	/* clang-format on */
	//	Add your own code
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	DCS210PCClass::pipe_factory_after
}
//--------------------------------------------------------
/**
 *	Method     : DCS210PCClass::command_factory()
 *	Description: Create the command object(s)
 *                and store them in the command list
 */
//--------------------------------------------------------
void DCS210PCClass::command_factory()
{
	/*----- PROTECTED REGION ID(DCS210PCClass::command_factory_before) ENABLED START -----*/
	/* clang-format on */
	//	Add your own code
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	DCS210PCClass::command_factory_before


	/*----- PROTECTED REGION ID(DCS210PCClass::command_factory_after) ENABLED START -----*/
	/* clang-format on */
	//	Add your own code
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	DCS210PCClass::command_factory_after
}

//===================================================================
//	Dynamic attributes related methods
//===================================================================

//--------------------------------------------------------
/**
 * method : 		DCS210PCClass::create_static_attribute_list
 * description : 	Create the a list of static attributes
 *
 * @param	att_list	the created attribute list
 */
//--------------------------------------------------------
void DCS210PCClass::create_static_attribute_list(std::vector<Tango::Attr *> &att_list)
{
	for (unsigned long i=0 ; i<att_list.size() ; i++)
	{
		std::string att_name(att_list[i]->get_name());
		std::transform(att_name.begin(), att_name.end(), att_name.begin(), ::tolower);
		defaultAttList.push_back(att_name);
	}

	TANGO_LOG_INFO << defaultAttList.size() << " attributes in default list" << std::endl;

	/*----- PROTECTED REGION ID(DCS210PCClass::create_static_att_list) ENABLED START -----*/
	/* clang-format on */
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	DCS210PCClass::create_static_att_list
}


//--------------------------------------------------------
/**
 * method : 		DCS210PCClass::erase_dynamic_attributes
 * description : 	delete the dynamic attributes if any.
 *
 * @param	devlist_ptr	the device list pointer
 * @param	list of all attributes
 */
//--------------------------------------------------------
void DCS210PCClass::erase_dynamic_attributes(const Tango::DevVarStringArray *devlist_ptr, std::vector<Tango::Attr *> &att_list)
{
	Tango::Util *tg = Tango::Util::instance();

	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		Tango::DeviceImpl *dev_impl = tg->get_device_by_name(((std::string)(*devlist_ptr)[i]).c_str());
		DCS210PC *dev = static_cast<DCS210PC *> (dev_impl);

		std::vector<Tango::Attribute *> &dev_att_list = dev->get_device_attr()->get_attribute_list();
		std::vector<Tango::Attribute *>::iterator ite_att;
		for (ite_att=dev_att_list.begin() ; ite_att != dev_att_list.end() ; ++ite_att)
		{
			std::string att_name((*ite_att)->get_name_lower());
			if ((att_name == "state") || (att_name == "status"))
				continue;
			std::vector<std::string>::iterator ite_str = find(defaultAttList.begin(), defaultAttList.end(), att_name);
			if (ite_str == defaultAttList.end())
			{
				TANGO_LOG_INFO << att_name << " is a UNWANTED dynamic attribute for device " << (*devlist_ptr)[i] << std::endl;
				Tango::Attribute &att = dev->get_device_attr()->get_attr_by_name(att_name.c_str());
				dev->remove_attribute(att_list[att.get_attr_idx()], true, false);
				--ite_att;
			}
		}
	}
	/*----- PROTECTED REGION ID(DCS210PCClass::erase_dynamic_attributes) ENABLED START -----*/
	/* clang-format on */
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	DCS210PCClass::erase_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Method     : DCS210PCClass::get_attr_object_by_name()
 *	Description: returns Tango::Attr * object found by name
 */
//--------------------------------------------------------
Tango::Attr *DCS210PCClass::get_attr_object_by_name(std::vector<Tango::Attr *> &att_list, std::string attname)
{
	std::vector<Tango::Attr *>::iterator it;
	for (it=att_list.begin() ; it<att_list.end() ; ++it)
		if ((*it)->get_name()==attname)
			return (*it);
	//	Attr does not exist
	return nullptr;
}


/*----- PROTECTED REGION ID(DCS210PCClass::Additional Methods) ENABLED START -----*/
/* clang-format on */
/* clang-format off */
/*----- PROTECTED REGION END -----*/	//	DCS210PCClass::Additional Methods
} //	namespace
