/*----- PROTECTED REGION ID(DCS210PC.h) ENABLED START -----*/
/* clang-format on */
//=============================================================================
//
// file :        DCS210PC.h
//
// description : Include file for the DCS210PC class
//
//
//
// This file is part of Tango device class.
//
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
//
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef DCS210PC_H
#define DCS210PC_H

#include <tango/tango.h>
#include "serial_port.h"

/* clang-format off */
/*----- PROTECTED REGION END -----*/	//	DCS210PC.h

#ifdef TANGO_LOG
	// cppTango after c934adea (Merge branch 'remove-cout-definition' into 'main', 2022-05-23)
	// nothing to do
#else
	// cppTango 9.3-backports and older
	#define TANGO_LOG       cout
	#define TANGO_LOG_INFO  cout2
	#define TANGO_LOG_DEBUG cout3
#endif // TANGO_LOG

/**
 *  DCS210PC class description:
 *    
 */


namespace DCS210PC_ns
{
/*----- PROTECTED REGION ID(DCS210PC::Additional Class Declarations) ENABLED START -----*/
/* clang-format on */
//	Additional Class Declarations
/* clang-format off */
/*----- PROTECTED REGION END -----*/	//	DCS210PC::Additional Class Declarations

class DCS210PC : public TANGO_BASE_CLASS
{

/*----- PROTECTED REGION ID(DCS210PC::Data Members) ENABLED START -----*/
/* clang-format on */
//	Add your own data members
/* clang-format off */
int fd;
std::string count_ph;
/*----- PROTECTED REGION END -----*/	//	DCS210PC::Data Members

//	Device property data members
public:
	//	baudrade:	
	Tango::DevLong	baudrade;
	//	com:	
	std::string	com;

//	Attribute data members
public:
	Tango::DevString	*attr_photons_num_str_read;
	Tango::DevLong	*attr_photon_num_int_read;

//	Constructors and destructors
public:
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	DCS210PC(Tango::DeviceClass *cl,std::string &s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	DCS210PC(Tango::DeviceClass *cl,const char *s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device name
	 *	@param d	Device description.
	 */
	DCS210PC(Tango::DeviceClass *cl,const char *s,const char *d);
	/**
	 * The device object destructor.
	 */
	~DCS210PC();


//	Miscellaneous methods
public:
	/*
	 *	will be called at device destruction or at init command.
	 */
	void delete_device();
	/*
	 *	Initialize the device
	 */
	virtual void init_device();
	/*
	 *	Read the device properties from database
	 */
	void get_device_property();
	/*
	 *	Always executed method before execution command method.
	 */
	virtual void always_executed_hook();


//	Attribute methods
public:
	//--------------------------------------------------------
	/*
	 *	Method     : DCS210PC::read_attr_hardware()
	 *	Description: Hardware acquisition for attributes.
	 */
	//--------------------------------------------------------
	virtual void read_attr_hardware(std::vector<long> &attr_list);

/**
 *	Attribute photons_num_str related methods
 *
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
	virtual void read_photons_num_str(Tango::Attribute &attr);
	virtual bool is_photons_num_str_allowed(Tango::AttReqType type);
/**
 *	Attribute photon_num_int related methods
 *
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Spectrum max = 100000
 */
	virtual void read_photon_num_int(Tango::Attribute &attr);
	virtual bool is_photon_num_int_allowed(Tango::AttReqType type);


	//--------------------------------------------------------
	/**
	 *	Method     : DCS210PC::add_dynamic_attributes()
	 *	Description: Add dynamic attributes if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_attributes();




//	Command related methods
public:


	//--------------------------------------------------------
	/**
	 *	Method     : DCS210PC::add_dynamic_commands()
	 *	Description: Add dynamic commands if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_commands();

/*----- PROTECTED REGION ID(DCS210PC::Additional Method prototypes) ENABLED START -----*/
/* clang-format on */
//	Additional Method prototypes
/* clang-format off */
/*----- PROTECTED REGION END -----*/	//	DCS210PC::Additional Method prototypes
};

/*----- PROTECTED REGION ID(DCS210PC::Additional Classes Definitions) ENABLED START -----*/
/* clang-format on */
//	Additional Classes Definitions
/* clang-format off */
/*----- PROTECTED REGION END -----*/	//	DCS210PC::Additional Classes Definitions

}	//	End of namespace

#endif   //	DCS210PC_H
